/* ============================================================================
   AI Starter Kit Catalog — seed dataset
   ----------------------------------------------------------------------------
   A curated, editorially-rated directory of developer-facing AI starter kits,
   templates and reference applications.

   IMPORTANT: the `links` below point at real, well-known open-source projects.
   The numeric ratings (difficulty, timeToHelloWorld, maturity, ecosystem,
   costFriendliness, docsQuality, activityScore, popularity) and `bestFor` text
   are editorial estimates authored for this dashboard's demo dataset — they are
   comparative judgement calls, not published metrics. Swap in your own numbers
   in the Admin panel, or replace this file with a fetch() to your own API.
   ========================================================================== */

const KITS = [
  {
    id: "vercel-ai-sdk-starter",
    name: "Vercel AI SDK Starter",
    org: "Vercel",
    category: "Full-Stack Web App",
    languages: ["TypeScript", "React", "Next.js"],
    models: ["OpenAI", "Anthropic", "Google Gemini", "Mistral", "Ollama"],
    license: "MIT",
    difficulty: 2,
    timeToHelloWorld: 10,
    maturity: 9,
    ecosystem: 10,
    costFriendliness: 7,
    docsQuality: 9,
    hasUI: true,
    hasBackend: false,
    hasEvals: false,
    requiresKey: true,
    localFirst: false,
    activityScore: 9,
    popularity: 96,
    stars: 21000,
    pricing: "Free / OSS (you pay model usage)",
    bestFor:
      "Shipping a production chat or generative UI feature into an existing Next.js app tonight.",
    repo: "https://github.com/vercel/ai",
    docs: "https://sdk.vercel.ai/docs",
  },
  {
    id: "langchain-quickstart",
    name: "LangChain Quickstart",
    org: "LangChain",
    category: "Agent Framework",
    languages: ["Python", "TypeScript"],
    models: ["OpenAI", "Anthropic", "Google Gemini", "Ollama", "Hugging Face"],
    license: "MIT",
    difficulty: 4,
    timeToHelloWorld: 20,
    maturity: 9,
    ecosystem: 10,
    costFriendliness: 8,
    docsQuality: 8,
    hasUI: false,
    hasBackend: false,
    hasEvals: false,
    requiresKey: true,
    localFirst: false,
    activityScore: 9,
    popularity: 94,
    stars: 96000,
    pricing: "Free / OSS",
    bestFor:
      "Teams that need every integration and a huge tutorial surface — accept the abstraction tax.",
    repo: "https://github.com/langchain-ai/langchain",
    docs: "https://python.langchain.com/docs/tutorials/",
  },
  {
    id: "llamaindex-starter",
    name: "LlamaIndex Starter",
    org: "LlamaIndex",
    category: "RAG / Retrieval",
    languages: ["Python", "TypeScript"],
    models: ["OpenAI", "Anthropic", "Google Gemini", "Ollama", "Cohere"],
    license: "MIT",
    difficulty: 3,
    timeToHelloWorld: 20,
    maturity: 9,
    ecosystem: 10,
    costFriendliness: 8,
    docsQuality: 9,
    hasUI: false,
    hasBackend: false,
    hasEvals: true,
    requiresKey: true,
    localFirst: false,
    activityScore: 9,
    popularity: 88,
    stars: 38000,
    pricing: "Free / OSS",
    bestFor:
      "Getting from a folder of PDFs to answerable, cited retrieval in an afternoon.",
    repo: "https://github.com/run-llama/llama_index",
    docs: "https://docs.llamaindex.ai/",
  },
  {
    id: "openai-cookbook",
    name: "OpenAI Cookbook",
    org: "OpenAI",
    category: "Reference / Cookbook",
    languages: ["Python", "TypeScript"],
    models: ["OpenAI"],
    license: "MIT",
    difficulty: 2,
    timeToHelloWorld: 10,
    maturity: 9,
    ecosystem: 7,
    costFriendliness: 7,
    docsQuality: 9,
    hasUI: false,
    hasBackend: false,
    hasEvals: true,
    requiresKey: true,
    localFirst: false,
    activityScore: 9,
    popularity: 90,
    stars: 62000,
    pricing: "Free / OSS (you pay model usage)",
    bestFor:
      "Copy-paste recipes for structured outputs, embeddings and tool calling on the OpenAI API.",
    repo: "https://github.com/openai/openai-cookbook",
    docs: "https://cookbook.openai.com/",
  },
  {
    id: "anthropic-cookbook",
    name: "Anthropic Cookbook",
    org: "Anthropic",
    category: "Reference / Cookbook",
    languages: ["Python", "Jupyter"],
    models: ["Anthropic"],
    license: "MIT",
    difficulty: 2,
    timeToHelloWorld: 15,
    maturity: 8,
    ecosystem: 6,
    costFriendliness: 7,
    docsQuality: 9,
    hasUI: false,
    hasBackend: false,
    hasEvals: true,
    requiresKey: true,
    localFirst: false,
    activityScore: 8,
    popularity: 82,
    stars: 13000,
    pricing: "Free / OSS (you pay model usage)",
    bestFor:
      "Learning prompt patterns, tool use and vision workflows for Claude models.",
    repo: "https://github.com/anthropics/anthropic-cookbook",
    docs: "https://docs.anthropic.com/",
  },
  {
    id: "streamlit-llm-app",
    name: "Streamlit LLM App Starter",
    org: "Streamlit",
    category: "Data & Notebook App",
    languages: ["Python"],
    models: ["OpenAI", "Anthropic", "Ollama", "Hugging Face"],
    license: "Apache-2.0",
    difficulty: 1,
    timeToHelloWorld: 5,
    maturity: 8,
    ecosystem: 8,
    costFriendliness: 8,
    docsQuality: 8,
    hasUI: true,
    hasBackend: false,
    hasEvals: false,
    requiresKey: true,
    localFirst: true,
    activityScore: 7,
    popularity: 85,
    stars: 35000,
    pricing: "Free / OSS",
    bestFor:
      "The fastest path from a Python script to a shareable internal AI demo — no frontend code at all.",
    repo: "https://github.com/streamlit/streamlit",
    docs: "https://docs.streamlit.io/",
  },
  {
    id: "gradio-interface",
    name: "Gradio Interface Starter",
    org: "Hugging Face",
    category: "Data & Notebook App",
    languages: ["Python", "Jupyter"],
    models: ["Hugging Face", "OpenAI", "Ollama"],
    license: "Apache-2.0",
    difficulty: 1,
    timeToHelloWorld: 5,
    maturity: 9,
    ecosystem: 9,
    costFriendliness: 9,
    docsQuality: 8,
    hasUI: true,
    hasBackend: false,
    hasEvals: false,
    requiresKey: false,
    localFirst: true,
    activityScore: 8,
    popularity: 89,
    stars: 37000,
    pricing: "Free / OSS",
    bestFor:
      "Standing up a model demo UI in five lines and sharing it with a public link.",
    repo: "https://github.com/gradio-app/gradio",
    docs: "https://www.gradio.app/guides/quickstart",
  },
  {
    id: "ollama-playground",
    name: "Ollama Local Playground",
    org: "Ollama",
    category: "Local / Self-Hosted",
    languages: ["Go", "Shell", "Any (HTTP API)"],
    models: ["Llama", "Mistral", "Gemma", "Qwen", "Phi"],
    license: "MIT",
    difficulty: 1,
    timeToHelloWorld: 5,
    maturity: 8,
    ecosystem: 8,
    costFriendliness: 10,
    docsQuality: 8,
    hasUI: true,
    hasBackend: false,
    hasEvals: false,
    requiresKey: false,
    localFirst: true,
    activityScore: 9,
    popularity: 91,
    stars: 100000,
    pricing: "Free / OSS (your hardware)",
    bestFor:
      "Running models entirely on your laptop with zero API keys — the best default for privacy-sensitive work.",
    repo: "https://github.com/ollama/ollama",
    docs: "https://docs.ollama.com/",
  },
  {
    id: "llama-cpp-quickstart",
    name: "llama.cpp Quickstart",
    org: "ggml-org",
    category: "Model Serving / Inference",
    languages: ["C++", "Python"],
    models: ["Llama", "Mistral", "Gemma", "Qwen"],
    license: "MIT",
    difficulty: 3,
    timeToHelloWorld: 25,
    maturity: 9,
    ecosystem: 9,
    costFriendliness: 10,
    docsQuality: 7,
    hasUI: true,
    hasBackend: true,
    hasEvals: false,
    requiresKey: false,
    localFirst: true,
    activityScore: 10,
    popularity: 87,
    stars: 70000,
    pricing: "Free / OSS",
    bestFor: "Quantised CPU/GPU inference with no Python in the critical path.",
    repo: "https://github.com/ggml-org/llama.cpp",
    docs: "https://github.com/ggml-org/llama.cpp/tree/master/examples",
  },
  {
    id: "vllm-serving",
    name: "vLLM Serving Starter",
    org: "vLLM Project",
    category: "Model Serving / Inference",
    languages: ["Python"],
    models: ["Llama", "Mistral", "Qwen", "Gemma"],
    license: "Apache-2.0",
    difficulty: 4,
    timeToHelloWorld: 45,
    maturity: 8,
    ecosystem: 8,
    costFriendliness: 8,
    docsQuality: 8,
    hasUI: false,
    hasBackend: true,
    hasEvals: false,
    requiresKey: false,
    localFirst: true,
    activityScore: 9,
    popularity: 78,
    stars: 46000,
    pricing: "Free / OSS (GPU required)",
    bestFor:
      "Throughput-heavy self-hosted inference when one request at a time is no longer enough.",
    repo: "https://github.com/vllm-project/vllm",
    docs: "https://docs.vllm.ai/",
  },
  {
    id: "llamafile-bundle",
    name: "llamafile Single-File Bundle",
    org: "Mozilla.ai",
    category: "Local / Self-Hosted",
    languages: ["C++", "Shell"],
    models: ["Llama", "Mistral", "Phi"],
    license: "Apache-2.0",
    difficulty: 1,
    timeToHelloWorld: 5,
    maturity: 7,
    ecosystem: 5,
    costFriendliness: 10,
    docsQuality: 7,
    hasUI: true,
    hasBackend: true,
    hasEvals: false,
    requiresKey: false,
    localFirst: true,
    activityScore: 7,
    popularity: 62,
    stars: 22000,
    pricing: "Free / OSS",
    bestFor:
      "Distributing one runnable executable that serves a model on any machine — no installs, no deps.",
    repo: "https://github.com/mozilla-ai/llamafile",
    docs: "https://docs.mozilla.ai/llamafile/",
  },
  {
    id: "llamafile",
    name: "WebGPU Browser LLM Starter",
    org: "MLC LLM",
    category: "Local / Self-Hosted",
    languages: ["TypeScript", "Python"],
    models: ["Llama", "Phi", "Gemma", "Mistral"],
    license: "Apache-2.0",
    difficulty: 4,
    timeToHelloWorld: 40,
    maturity: 6,
    ecosystem: 6,
    costFriendliness: 9,
    docsQuality: 6,
    hasUI: true,
    hasBackend: false,
    hasEvals: false,
    requiresKey: false,
    localFirst: true,
    activityScore: 8,
    popularity: 68,
    stars: 20000,
    pricing: "Free / OSS",
    bestFor:
      "Running inference in the browser via WebGPU/WebLLM — zero server, zero per-token cost.",
    repo: "https://github.com/mlc-ai/web-llm",
    docs: "https://webllm.mlc.ai/docs/",
  },
  {
    id: "nextjs-rag-template",
    name: "Next.js RAG Chat Template",
    org: "Vercel Templates",
    category: "RAG / Retrieval",
    languages: ["TypeScript", "Next.js"],
    models: ["OpenAI", "Anthropic", "Google Gemini"],
    license: "MIT",
    difficulty: 3,
    timeToHelloWorld: 25,
    maturity: 8,
    ecosystem: 9,
    costFriendliness: 7,
    docsQuality: 8,
    hasUI: true,
    hasBackend: true,
    hasEvals: false,
    requiresKey: true,
    localFirst: false,
    activityScore: 8,
    popularity: 84,
    stars: 9000,
    pricing: "Free / OSS (you pay hosting + model usage)",
    bestFor:
      "A deployable chat-with-your-docs app with streaming, citations and a real UI already wired up.",
    repo: "https://github.com/vercel/ai-chatbot",
    docs: "https://sdk.vercel.ai/docs/guides/rag-chatbot",
  },
  {
    id: "ragflow-platform",
    name: "RAGFlow Pipeline Starter",
    org: "InfiniFlow",
    category: "RAG / Retrieval",
    languages: ["Python", "TypeScript"],
    models: ["OpenAI", "Ollama", "Local models"],
    license: "Apache-2.0",
    difficulty: 4,
    timeToHelloWorld: 60,
    maturity: 7,
    ecosystem: 6,
    costFriendliness: 9,
    docsQuality: 7,
    hasUI: true,
    hasBackend: true,
    hasEvals: true,
    requiresKey: false,
    localFirst: true,
    activityScore: 8,
    popularity: 74,
    stars: 42000,
    pricing: "Free / OSS (self-host)",
    bestFor:
      "Deep document parsing — tables, scanned PDFs — where naive chunking keeps failing you.",
    repo: "https://github.com/infiniflow/ragflow",
    docs: "https://ragflow.io/docs/dev/",
  },
  {
    id: "qdrant-rag-starter",
    name: "Qdrant Vector Search Starter",
    org: "Qdrant",
    category: "RAG / Retrieval",
    languages: ["Python", "Rust"],
    models: ["Any (BYO embeddings)"],
    license: "Apache-2.0",
    difficulty: 3,
    timeToHelloWorld: 20,
    maturity: 8,
    ecosystem: 8,
    costFriendliness: 8,
    docsQuality: 9,
    hasUI: true,
    hasBackend: true,
    hasEvals: false,
    requiresKey: false,
    localFirst: true,
    activityScore: 8,
    popularity: 73,
    stars: 23000,
    pricing: "Free / OSS (or managed cloud)",
    bestFor:
      "Adding filtered vector retrieval to an existing app without committing to a heavyweight framework.",
    repo: "https://github.com/qdrant/qdrant",
    docs: "https://qdrant.tech/documentation/quickstart/",
  },
  {
    id: "chroma-starter",
    name: "Chroma Embedding Store Starter",
    org: "Chroma",
    category: "RAG / Retrieval",
    languages: ["Python", "TypeScript"],
    models: ["Any (BYO embeddings)"],
    license: "Apache-2.0",
    difficulty: 1,
    timeToHelloWorld: 10,
    maturity: 8,
    ecosystem: 8,
    costFriendliness: 9,
    docsQuality: 8,
    hasUI: false,
    hasBackend: false,
    hasEvals: false,
    requiresKey: false,
    localFirst: true,
    activityScore: 8,
    popularity: 79,
    stars: 19000,
    pricing: "Free / OSS",
    bestFor:
      "Prototyping a retrieval idea in-memory before you pick a real vector database.",
    repo: "https://github.com/chroma-core/chroma",
    docs: "https://docs.trychroma.com/",
  },
  {
    id: "crewai-starter",
    name: "CrewAI Multi-Agent Starter",
    org: "CrewAI",
    category: "Agent Framework",
    languages: ["Python"],
    models: ["OpenAI", "Anthropic", "Google Gemini", "Ollama"],
    license: "MIT",
    difficulty: 3,
    timeToHelloWorld: 20,
    maturity: 7,
    ecosystem: 8,
    costFriendliness: 8,
    docsQuality: 8,
    hasUI: false,
    hasBackend: false,
    hasEvals: false,
    requiresKey: true,
    localFirst: false,
    activityScore: 9,
    popularity: 83,
    stars: 30000,
    pricing: "Free / OSS (paid cloud tier)",
    bestFor:
      "Modelling a business workflow as a team of role-playing agents instead of one giant prompt.",
    repo: "https://github.com/crewAIInc/crewAI",
    docs: "https://docs.crewai.com/",
  },
  {
    id: "autogen-studio",
    name: "AutoGen Studio",
    org: "Microsoft",
    category: "Agent Framework",
    languages: ["Python", "TypeScript"],
    models: ["OpenAI", "Anthropic", "Ollama", "Azure OpenAI"],
    license: "MIT",
    difficulty: 4,
    timeToHelloWorld: 35,
    maturity: 8,
    ecosystem: 8,
    costFriendliness: 7,
    docsQuality: 8,
    hasUI: true,
    hasBackend: true,
    hasEvals: true,
    requiresKey: true,
    localFirst: false,
    activityScore: 8,
    popularity: 81,
    stars: 50000,
    pricing: "Free / OSS",
    bestFor:
      "Research-style multi-agent conversations with a visual builder and event tracing built in.",
    repo: "https://github.com/microsoft/autogen",
    docs: "https://microsoft.github.io/autogen/",
  },
  {
    id: "langgraph-agent-template",
    name: "LangGraph Agent Template",
    org: "LangChain",
    category: "Agent Framework",
    languages: ["Python", "TypeScript"],
    models: ["OpenAI", "Anthropic", "Google Gemini"],
    license: "MIT",
    difficulty: 5,
    timeToHelloWorld: 40,
    maturity: 8,
    ecosystem: 8,
    costFriendliness: 7,
    docsQuality: 8,
    hasUI: false,
    hasBackend: true,
    hasEvals: true,
    requiresKey: true,
    localFirst: false,
    activityScore: 10,
    popularity: 80,
    stars: 14000,
    pricing: "Free / OSS (paid platform tier)",
    bestFor:
      "Long-running, stateful agents with retries, human-in-the-loop and checkpointed memory.",
    repo: "https://github.com/langchain-ai/langgraph",
    docs: "https://langchain-ai.github.io/langgraph/",
  },
  {
    id: "openai-agents-sdk",
    name: "OpenAI Agents SDK Starter",
    org: "OpenAI",
    category: "Agent Framework",
    languages: ["Python", "TypeScript"],
    models: ["OpenAI"],
    license: "MIT",
    difficulty: 3,
    timeToHelloWorld: 15,
    maturity: 6,
    ecosystem: 5,
    costFriendliness: 7,
    docsQuality: 8,
    hasUI: false,
    hasBackend: false,
    hasEvals: true,
    requiresKey: true,
    localFirst: false,
    activityScore: 9,
    popularity: 84,
    stars: 16000,
    pricing: "Free / OSS (you pay model usage)",
    bestFor:
      "A small, explicit agent loop with handoffs and guardrails — minimal magic, fast to read.",
    repo: "https://github.com/openai/openai-agents-python",
    docs: "https://openai.github.io/openai-agents-python/",
  },
  {
    id: "google-adk",
    name: "Google Agent Development Kit",
    org: "Google",
    category: "Agent Framework",
    languages: ["Python", "Java"],
    models: ["Google Gemini", "Vertex AI", "Anthropic"],
    license: "Apache-2.0",
    difficulty: 4,
    timeToHelloWorld: 30,
    maturity: 7,
    ecosystem: 8,
    costFriendliness: 7,
    docsQuality: 8,
    hasUI: true,
    hasBackend: true,
    hasEvals: true,
    requiresKey: true,
    localFirst: false,
    activityScore: 9,
    popularity: 76,
    stars: 12000,
    pricing: "Free / OSS (you pay model usage)",
    bestFor:
      "Enterprise-flavoured agents that need evaluation, tracing and multi-agent orchestration on Vertex.",
    repo: "https://github.com/google/adk-python",
    docs: "https://google.github.io/adk-docs/",
  },
  {
    id: "aws-bedrock-agents",
    name: "AWS Bedrock Agents Starter",
    org: "AWS",
    category: "Enterprise / Cloud",
    languages: ["Python", "TypeScript"],
    models: ["Bedrock (Claude, Titan, Llama)"],
    license: "Apache-2.0",
    difficulty: 5,
    timeToHelloWorld: 60,
    maturity: 8,
    ecosystem: 8,
    costFriendliness: 5,
    docsQuality: 8,
    hasUI: false,
    hasBackend: true,
    hasEvals: true,
    requiresKey: true,
    localFirst: false,
    activityScore: 7,
    popularity: 66,
    stars: 4000,
    pricing: "Pay-as-you-go (AWS)",
    bestFor:
      "Teams already on AWS that need IAM-scoped agents talking to internal data sources.",
    repo: "https://github.com/awslabs/amazon-bedrock-agent-samples",
    docs: "https://docs.aws.amazon.com/bedrock/latest/userguide/agents.html",
  },
  {
    id: "azure-ai-foundry-samples",
    name: "Azure AI Foundry Samples",
    org: "Microsoft",
    category: "Enterprise / Cloud",
    languages: ["Python", "C#", "TypeScript"],
    models: ["Azure OpenAI", "Phi", "Llama"],
    license: "MIT",
    difficulty: 5,
    timeToHelloWorld: 60,
    maturity: 8,
    ecosystem: 8,
    costFriendliness: 5,
    docsQuality: 8,
    hasUI: true,
    hasBackend: true,
    hasEvals: true,
    requiresKey: true,
    localFirst: false,
    activityScore: 8,
    popularity: 70,
    stars: 3000,
    pricing: "Pay-as-you-go (Azure)",
    bestFor:
      "Regulated environments that need private networking, content filters and audit trails out of the box.",
    repo: "https://github.com/Azure-Samples/azureai-samples",
    docs: "https://learn.microsoft.com/azure/ai-foundry/",
  },
  {
    id: "supabase-vector-starter",
    name: "Supabase Vector + Auth Starter",
    org: "Supabase",
    category: "Full-Stack Web App",
    languages: ["TypeScript", "Postgres"],
    models: ["OpenAI", "Google Gemini", "Ollama"],
    license: "Apache-2.0",
    difficulty: 3,
    timeToHelloWorld: 30,
    maturity: 8,
    ecosystem: 8,
    costFriendliness: 8,
    docsQuality: 9,
    hasUI: true,
    hasBackend: true,
    hasEvals: false,
    requiresKey: true,
    localFirst: false,
    activityScore: 8,
    popularity: 77,
    stars: 8000,
    pricing: "Free tier + usage-based",
    bestFor:
      "One Postgres for auth, rows and embeddings — the shortest stack that still looks like a real product.",
    repo: "https://github.com/supabase/supabase",
    docs: "https://supabase.com/docs/guides/ai",
  },
  {
    id: "firebase-genkit",
    name: "Firebase Genkit Starter",
    org: "Google",
    category: "Full-Stack Web App",
    languages: ["TypeScript", "Go", "Python"],
    models: ["Google Gemini", "OpenAI", "Anthropic", "Ollama"],
    license: "Apache-2.0",
    difficulty: 3,
    timeToHelloWorld: 25,
    maturity: 7,
    ecosystem: 7,
    costFriendliness: 7,
    docsQuality: 8,
    hasUI: false,
    hasBackend: true,
    hasEvals: true,
    requiresKey: true,
    localFirst: false,
    activityScore: 8,
    popularity: 68,
    stars: 4000,
    pricing: "Free / OSS (you pay cloud usage)",
    bestFor:
      "Shipping AI flows with a local dev UI, tracing and evaluations wired in from the first commit.",
    repo: "https://github.com/firebase/genkit",
    docs: "https://firebase.google.com/docs/genkit",
  },
  {
    id: "huggingface-transformers-starter",
    name: "Hugging Face Transformers Starter",
    org: "Hugging Face",
    category: "Fine-Tuning",
    languages: ["Python"],
    models: ["Hugging Face Hub (300k+ models)"],
    license: "Apache-2.0",
    difficulty: 3,
    timeToHelloWorld: 15,
    maturity: 10,
    ecosystem: 10,
    costFriendliness: 8,
    docsQuality: 9,
    hasUI: false,
    hasBackend: false,
    hasEvals: true,
    requiresKey: false,
    localFirst: true,
    activityScore: 9,
    popularity: 95,
    stars: 130000,
    pricing: "Free / OSS",
    bestFor:
      "The default on-ramp for running, fine-tuning or quantising any open model yourself.",
    repo: "https://github.com/huggingface/transformers",
    docs: "https://huggingface.co/docs/transformers/index",
  },
  {
    id: "peft-lora-tuning",
    name: "PEFT / LoRA Fine-Tuning Kit",
    org: "Hugging Face",
    category: "Fine-Tuning",
    languages: ["Python"],
    models: ["Llama", "Mistral", "Qwen", "Gemma"],
    license: "Apache-2.0",
    difficulty: 5,
    timeToHelloWorld: 90,
    maturity: 8,
    ecosystem: 8,
    costFriendliness: 7,
    docsQuality: 8,
    hasUI: false,
    hasBackend: false,
    hasEvals: false,
    requiresKey: false,
    localFirst: true,
    activityScore: 8,
    popularity: 72,
    stars: 17000,
    pricing: "Free / OSS (GPU required)",
    bestFor:
      "Adapting a base model to your domain on a single GPU without full fine-tuning costs.",
    repo: "https://github.com/huggingface/peft",
    docs: "https://huggingface.co/docs/peft/index",
  },
  {
    id: "unsloth-notebook",
    name: "Unsloth Fast Fine-Tuning Notebooks",
    org: "Unsloth AI",
    category: "Fine-Tuning",
    languages: ["Python", "Jupyter"],
    models: ["Llama", "Mistral", "Gemma", "Qwen"],
    license: "Apache-2.0",
    difficulty: 3,
    timeToHelloWorld: 45,
    maturity: 7,
    ecosystem: 6,
    costFriendliness: 9,
    docsQuality: 8,
    hasUI: false,
    hasBackend: false,
    hasEvals: false,
    requiresKey: false,
    localFirst: true,
    activityScore: 8,
    popularity: 69,
    stars: 40000,
    pricing: "Free / OSS (GPU required)",
    bestFor:
      "Fine-tuning on a free Colab GPU when memory, not patience, is the constraint.",
    repo: "https://github.com/unslothai/unsloth",
    docs: "https://docs.unsloth.ai/",
  },
  {
    id: "axolotl-tuning",
    name: "Axolotl Config-Driven Tuning",
    org: "Axolotl AI",
    category: "Fine-Tuning",
    languages: ["Python", "YAML"],
    models: ["Llama", "Mistral", "Qwen", "Phi"],
    license: "Apache-2.0",
    difficulty: 5,
    timeToHelloWorld: 120,
    maturity: 7,
    ecosystem: 6,
    costFriendliness: 7,
    docsQuality: 7,
    hasUI: false,
    hasBackend: false,
    hasEvals: false,
    requiresKey: false,
    localFirst: true,
    activityScore: 7,
    popularity: 61,
    stars: 9000,
    pricing: "Free / OSS (GPU required)",
    bestFor:
      "Reproducible multi-GPU training runs driven entirely by versioned YAML configs.",
    repo: "https://github.com/axolotl-ai-cloud/axolotl",
    docs: "https://docs.axolotl.ai/",
  },
  {
    id: "langfuse-observability",
    name: "Langfuse Observability Starter",
    org: "Langfuse",
    category: "Evaluation / Observability",
    languages: ["TypeScript", "Python"],
    models: ["Any (model-agnostic)"],
    license: "MIT",
    difficulty: 3,
    timeToHelloWorld: 20,
    maturity: 8,
    ecosystem: 7,
    costFriendliness: 8,
    docsQuality: 9,
    hasUI: true,
    hasBackend: true,
    hasEvals: true,
    requiresKey: false,
    localFirst: true,
    activityScore: 9,
    popularity: 75,
    stars: 10000,
    pricing: "Free / OSS (paid cloud tier)",
    bestFor:
      "Seeing what your prompts actually did in production — traces, costs and scores in one place.",
    repo: "https://github.com/langfuse/langfuse",
    docs: "https://langfuse.com/docs",
  },
  {
    id: "ragas-evaluation",
    name: "Ragas RAG Evaluation Starter",
    org: "Exploding Gradients",
    category: "Evaluation / Observability",
    languages: ["Python"],
    models: ["OpenAI", "Any (judge model)"],
    license: "Apache-2.0",
    difficulty: 4,
    timeToHelloWorld: 45,
    maturity: 7,
    ecosystem: 6,
    costFriendliness: 7,
    docsQuality: 8,
    hasUI: false,
    hasBackend: false,
    hasEvals: true,
    requiresKey: true,
    localFirst: false,
    activityScore: 7,
    popularity: 64,
    stars: 8000,
    pricing: "Free / OSS",
    bestFor:
      "Putting numbers — faithfulness, context precision — on a RAG pipeline before you ship it.",
    repo: "https://github.com/explodinggradients/ragas",
    docs: "https://docs.ragas.io/",
  },
  {
    id: "promptfoo-evals",
    name: "Promptfoo Eval Starter",
    org: "Promptfoo",
    category: "Evaluation / Observability",
    languages: ["TypeScript", "YAML"],
    models: ["OpenAI", "Anthropic", "Google Gemini", "Ollama", "Mistral"],
    license: "MIT",
    difficulty: 2,
    timeToHelloWorld: 15,
    maturity: 8,
    ecosystem: 7,
    costFriendliness: 9,
    docsQuality: 9,
    hasUI: true,
    hasBackend: false,
    hasEvals: true,
    requiresKey: true,
    localFirst: true,
    activityScore: 9,
    popularity: 71,
    stars: 6000,
    pricing: "Free / OSS",
    bestFor:
      "A CLI-first regression suite that catches prompt changes before your users do.",
    repo: "https://github.com/promptfoo/promptfoo",
    docs: "https://www.promptfoo.dev/docs/quickstart/",
  },
  {
    id: "opik-eval-starter",
    name: "Opik Experiment Tracking",
    org: "Comet",
    category: "Evaluation / Observability",
    languages: ["Python", "TypeScript"],
    models: ["Any (model-agnostic)"],
    license: "Apache-2.0",
    difficulty: 3,
    timeToHelloWorld: 30,
    maturity: 7,
    ecosystem: 6,
    costFriendliness: 8,
    docsQuality: 8,
    hasUI: true,
    hasBackend: true,
    hasEvals: true,
    requiresKey: false,
    localFirst: true,
    activityScore: 8,
    popularity: 58,
    stars: 7000,
    pricing: "Free / OSS (paid cloud tier)",
    bestFor:
      "Tracking prompt experiments side by side the way you already track ML runs.",
    repo: "https://github.com/comet-ml/opik",
    docs: "https://www.comet.com/docs/opik/",
  },
  {
    id: "fiftyone-vision",
    name: "FiftyOne Vision Dataset Starter",
    org: "Voxel51",
    category: "Vision / Multimodal",
    languages: ["Python"],
    models: ["Any (model-agnostic)"],
    license: "Apache-2.0",
    difficulty: 3,
    timeToHelloWorld: 30,
    maturity: 8,
    ecosystem: 7,
    costFriendliness: 9,
    docsQuality: 8,
    hasUI: true,
    hasBackend: false,
    hasEvals: false,
    requiresKey: false,
    localFirst: true,
    activityScore: 8,
    popularity: 63,
    stars: 9000,
    pricing: "Free / OSS (paid enterprise tier)",
    bestFor:
      "Curating, visualising and debugging messy image datasets before they poison your model.",
    repo: "https://github.com/voxel51/fiftyone",
    docs: "https://docs.voxel51.com/",
  },
  {
    id: "ultralytics-yolo",
    name: "Ultralytics YOLO Training Kit",
    org: "Ultralytics",
    category: "Vision / Multimodal",
    languages: ["Python"],
    models: ["YOLO (detection, segmentation, pose)"],
    license: "AGPL-3.0",
    difficulty: 3,
    timeToHelloWorld: 20,
    maturity: 9,
    ecosystem: 9,
    costFriendliness: 9,
    docsQuality: 9,
    hasUI: false,
    hasBackend: false,
    hasEvals: true,
    requiresKey: false,
    localFirst: true,
    activityScore: 9,
    popularity: 86,
    stars: 45000,
    pricing: "Free / OSS (AGPL or commercial licence)",
    bestFor:
      "Real-time object detection where you need a working model today and training tomorrow.",
    repo: "https://github.com/ultralytics/ultralytics",
    docs: "https://docs.ultralytics.com/",
  },
  {
    id: "comfyui-workflows",
    name: "ComfyUI Workflow Starter",
    org: "Comfy Org",
    category: "Image / Generation",
    languages: ["Python"],
    models: ["Stable Diffusion", "Flux", "SDXL"],
    license: "GPL-3.0",
    difficulty: 4,
    timeToHelloWorld: 45,
    maturity: 8,
    ecosystem: 10,
    costFriendliness: 9,
    docsQuality: 6,
    hasUI: true,
    hasBackend: true,
    hasEvals: false,
    requiresKey: false,
    localFirst: true,
    activityScore: 10,
    popularity: 88,
    stars: 80000,
    pricing: "Free / OSS",
    bestFor:
      "Node-graph image generation pipelines you can actually version, share and extend with custom nodes.",
    repo: "https://github.com/comfyanonymous/ComfyUI",
    docs: "https://docs.comfy.org/",
  },
  {
    id: "automatic1111-webui",
    name: "AUTOMATIC1111 WebUI",
    org: "AUTOMATIC1111",
    category: "Image / Generation",
    languages: ["Python"],
    models: ["Stable Diffusion", "SDXL"],
    license: "AGPL-3.0",
    difficulty: 2,
    timeToHelloWorld: 30,
    maturity: 8,
    ecosystem: 10,
    costFriendliness: 9,
    docsQuality: 6,
    hasUI: true,
    hasBackend: true,
    hasEvals: false,
    requiresKey: false,
    localFirst: true,
    activityScore: 7,
    popularity: 82,
    stars: 140000,
    pricing: "Free / OSS",
    bestFor:
      "The classic batteries-included diffusion UI with the largest extension library on the planet.",
    repo: "https://github.com/AUTOMATIC1111/stable-diffusion-webui",
    docs: "https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki",
  },
  {
    id: "diffusers-starter",
    name: "Hugging Face Diffusers Starter",
    org: "Hugging Face",
    category: "Image / Generation",
    languages: ["Python"],
    models: ["Stable Diffusion", "Flux", "SDXL", "Kandinsky"],
    license: "Apache-2.0",
    difficulty: 3,
    timeToHelloWorld: 20,
    maturity: 9,
    ecosystem: 9,
    costFriendliness: 9,
    docsQuality: 9,
    hasUI: false,
    hasBackend: false,
    hasEvals: false,
    requiresKey: false,
    localFirst: true,
    activityScore: 9,
    popularity: 84,
    stars: 28000,
    pricing: "Free / OSS (GPU recommended)",
    bestFor:
      "Scriptable diffusion when you need pipelines in code rather than clicking through a GUI.",
    repo: "https://github.com/huggingface/diffusers",
    docs: "https://huggingface.co/docs/diffusers/index",
  },
  {
    id: "whisper-cpp-starter",
    name: "whisper.cpp Transcription Starter",
    org: "ggml-org",
    category: "Audio / Speech",
    languages: ["C++", "Shell"],
    models: ["Whisper"],
    license: "MIT",
    difficulty: 2,
    timeToHelloWorld: 15,
    maturity: 8,
    ecosystem: 7,
    costFriendliness: 10,
    docsQuality: 7,
    hasUI: false,
    hasBackend: true,
    hasEvals: false,
    requiresKey: false,
    localFirst: true,
    activityScore: 8,
    popularity: 79,
    stars: 42000,
    pricing: "Free / OSS",
    bestFor:
      "Offline, fast speech-to-text on CPU — no cloud round trip and no per-minute billing.",
    repo: "https://github.com/ggml-org/whisper.cpp",
    docs: "https://github.com/ggml-org/whisper.cpp/tree/master/examples",
  },
  {
    id: "pipecat-voice",
    name: "Pipecat Voice Agent Starter",
    org: "Daily",
    category: "Audio / Speech",
    languages: ["Python"],
    models: ["OpenAI", "Anthropic", "Google Gemini", "Deepgram", "ElevenLabs"],
    license: "BSD-2-Clause",
    difficulty: 4,
    timeToHelloWorld: 40,
    maturity: 7,
    ecosystem: 7,
    costFriendliness: 6,
    docsQuality: 8,
    hasUI: false,
    hasBackend: true,
    hasEvals: false,
    requiresKey: true,
    localFirst: false,
    activityScore: 9,
    popularity: 67,
    stars: 6000,
    pricing: "Free / OSS (you pay STT/TTS/LLM usage)",
    bestFor:
      "Real-time voice agents — barge-in, interruption and turn-taking handled by the framework.",
    repo: "https://github.com/pipecat-ai/pipecat",
    docs: "https://docs.pipecat.ai/",
  },
  {
    id: "litellm-proxy",
    name: "LiteLLM Proxy Starter",
    org: "BerriAI",
    category: "Guardrails / Safety",
    languages: ["Python"],
    models: ["100+ providers behind one API"],
    license: "MIT",
    difficulty: 2,
    timeToHelloWorld: 15,
    maturity: 8,
    ecosystem: 7,
    costFriendliness: 8,
    docsQuality: 8,
    hasUI: true,
    hasBackend: true,
    hasEvals: false,
    requiresKey: true,
    localFirst: true,
    activityScore: 9,
    popularity: 76,
    stars: 20000,
    pricing: "Free / OSS",
    bestFor:
      "One OpenAI-shaped endpoint in front of every provider, with budgets, keys and fallbacks.",
    repo: "https://github.com/BerriAI/litellm",
    docs: "https://docs.litellm.ai/",
  },
  {
    id: "guardrails-ai-starter",
    name: "Guardrails AI Validation Starter",
    org: "Guardrails AI",
    category: "Guardrails / Safety",
    languages: ["Python"],
    models: ["OpenAI", "Anthropic", "Ollama", "Any (LLM-agnostic)"],
    license: "Apache-2.0",
    difficulty: 3,
    timeToHelloWorld: 25,
    maturity: 7,
    ecosystem: 6,
    costFriendliness: 8,
    docsQuality: 8,
    hasUI: false,
    hasBackend: false,
    hasEvals: true,
    requiresKey: true,
    localFirst: false,
    activityScore: 8,
    popularity: 65,
    stars: 6000,
    pricing: "Free / OSS (paid cloud tier)",
    bestFor:
      "Forcing structured, schema-valid model output instead of grepping raw text for JSON.",
    repo: "https://github.com/guardrails-ai/guardrails",
    docs: "https://www.guardrailsai.com/docs",
  },
  {
    id: "nemo-guardrails",
    name: "NVIDIA NeMo Guardrails",
    org: "NVIDIA",
    category: "Guardrails / Safety",
    languages: ["Python"],
    models: ["OpenAI", "Anthropic", "NVIDIA NIM", "Llama"],
    license: "Apache-2.0",
    difficulty: 4,
    timeToHelloWorld: 45,
    maturity: 7,
    ecosystem: 6,
    costFriendliness: 7,
    docsQuality: 8,
    hasUI: false,
    hasBackend: true,
    hasEvals: true,
    requiresKey: true,
    localFirst: false,
    activityScore: 8,
    popularity: 62,
    stars: 5000,
    pricing: "Free / OSS",
    bestFor:
      "Conversational policy rails — keep a bot on-topic and inside its lane without prompt whack-a-mole.",
    repo: "https://github.com/NVIDIA/NeMo-Guardrails",
    docs: "https://docs.nvidia.com/nemo/guardrails/",
  },
  {
    id: "mcp-quickstart",
    name: "MCP Server Quickstart",
    org: "Model Context Protocol",
    category: "Tooling / MCP",
    languages: ["TypeScript", "Python"],
    models: ["Any (host-agnostic)"],
    license: "MIT",
    difficulty: 3,
    timeToHelloWorld: 25,
    maturity: 7,
    ecosystem: 8,
    costFriendliness: 9,
    docsQuality: 9,
    hasUI: false,
    hasBackend: true,
    hasEvals: false,
    requiresKey: false,
    localFirst: true,
    activityScore: 10,
    popularity: 86,
    stars: 20000,
    pricing: "Free / OSS",
    bestFor:
      "Exposing your own tools and data to any MCP-capable assistant once, instead of per-client integrations.",
    repo: "https://github.com/modelcontextprotocol/servers",
    docs: "https://modelcontextprotocol.io/quickstart/server",
  },
  {
    id: "openai-realtime-starter",
    name: "Realtime API Voice Starter",
    org: "OpenAI",
    category: "Audio / Speech",
    languages: ["TypeScript", "Python"],
    models: ["OpenAI Realtime"],
    license: "MIT",
    difficulty: 4,
    timeToHelloWorld: 30,
    maturity: 6,
    ecosystem: 5,
    costFriendliness: 5,
    docsQuality: 8,
    hasUI: true,
    hasBackend: true,
    hasEvals: false,
    requiresKey: true,
    localFirst: false,
    activityScore: 8,
    popularity: 74,
    stars: 4000,
    pricing: "Pay-as-you-go (OpenAI)",
    bestFor:
      "Low-latency speech-to-speech over WebRTC when every extra round trip is audible.",
    repo: "https://github.com/openai/openai-realtime-console",
    docs: "https://platform.openai.com/docs/guides/realtime",
  },
  {
    id: "semantic-kernel-starter",
    name: "Semantic Kernel Starter",
    org: "Microsoft",
    category: "Enterprise / Cloud",
    languages: ["C#", "Python", "Java"],
    models: ["OpenAI", "Azure OpenAI", "Google Gemini", "Hugging Face"],
    license: "MIT",
    difficulty: 4,
    timeToHelloWorld: 40,
    maturity: 8,
    ecosystem: 8,
    costFriendliness: 7,
    docsQuality: 8,
    hasUI: false,
    hasBackend: false,
    hasEvals: false,
    requiresKey: true,
    localFirst: false,
    activityScore: 8,
    popularity: 69,
    stars: 25000,
    pricing: "Free / OSS",
    bestFor:
      ".NET shops that want plugins, planners and memory in the language their services already speak.",
    repo: "https://github.com/microsoft/semantic-kernel",
    docs: "https://learn.microsoft.com/semantic-kernel/",
  },
  {
    id: "dspy-optimizer",
    name: "DSPy Prompt Optimizer Starter",
    org: "Stanford NLP",
    category: "Evaluation / Observability",
    languages: ["Python"],
    models: ["OpenAI", "Anthropic", "Google Gemini", "Ollama"],
    license: "MIT",
    difficulty: 5,
    timeToHelloWorld: 60,
    maturity: 7,
    ecosystem: 6,
    costFriendliness: 7,
    docsQuality: 8,
    hasUI: false,
    hasBackend: false,
    hasEvals: true,
    requiresKey: true,
    localFirst: false,
    activityScore: 9,
    popularity: 71,
    stars: 20000,
    pricing: "Free / OSS",
    bestFor:
      "Replacing hand-tuned prompt strings with compiled, metric-driven programs.",
    repo: "https://github.com/stanfordnlp/dspy",
    docs: "https://dspy.ai/",
  },
  {
    id: "smith-agentic-bench",
    name: "Agentic Benchmark Harness",
    org: "Community",
    category: "Evaluation / Observability",
    languages: ["Python", "YAML"],
    models: ["OpenAI", "Anthropic", "Ollama"],
    license: "MIT",
    difficulty: 4,
    timeToHelloWorld: 50,
    maturity: 5,
    ecosystem: 4,
    costFriendliness: 7,
    docsQuality: 6,
    hasUI: false,
    hasBackend: false,
    hasEvals: true,
    requiresKey: true,
    localFirst: true,
    activityScore: 6,
    popularity: 45,
    stars: 1200,
    pricing: "Free / OSS",
    bestFor:
      "Scoring agent runs on task success and step count when you have no formal eval set yet.",
    repo: "https://github.com/openai/evals",
    docs: "https://github.com/openai/evals/blob/main/README.md",
  },
];

/* --------------------------------------------------------------------------
   Derived helpers — kept here so every module shares one source of truth.
   -------------------------------------------------------------------------- */

const CATEGORIES = [...new Set(KITS.map((k) => k.category))].sort();

const LANGUAGES = [...new Set(KITS.flatMap((k) => k.languages))].sort();

const LICENSES = [...new Set(KITS.map((k) => k.license))].sort();

const ADVANTAGE_LABELS = {
  hasUI: "Ships a UI",
  hasBackend: "Backend / service included",
  hasEvals: "Eval & tracing hooks",
  requiresKey: "Needs an API key",
  localFirst: "Runs fully local",
};

/** Weighted 0-10 score used for ranking and the radar/scatter charts. */
function computeKitScore(kit) {
  const raw =
    kit.maturity * 0.22 +
    kit.ecosystem * 0.16 +
    kit.docsQuality * 0.16 +
    kit.activityScore * 0.16 +
    kit.costFriendliness * 0.12 +
    (kit.popularity / 10) * 0.18;
  return Math.round(raw * 10) / 10;
}

/** 0-10 → 1-5 dot rating, friendlier to read than a decimal. */
function difficultyLabel(difficulty) {
  return (
    ["", "Beginner", "Easy", "Moderate", "Advanced", "Expert"][difficulty] || "Unknown"
  );
}

KITS.forEach((kit) => {
  kit.score = computeKitScore(kit);
});
